version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - snapsnapturtle
    groups:
      kotlin:
        patterns:
          - "jvm"
          - "plugin.spring"
          - "plugin.jpa"
      spring:
        patterns:
          - "org.springframework.boot"
          - "org.springframework.cloud"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - snapsnapturtle
