version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
    groups:
      react:
        patterns:
          - "jvm"
          - "plugin.spring"
          - "plugin.jpa"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
