#!/usr/bin/env sh

# Gather the staged files - to make sure changes are saved only for these files.
stagedFiles=$(git diff --staged --name-only)

# run spotless apply
./gradlew spotlessApply

status=$?

if [ "$status" = 0 ] ; then
    for file in $stagedFiles; do
      if test -f "$file"; then
        git add $file
      fi
    done

    exit 0
else
    echo 1>&2 "./gradlew spotlessApply found violations it could not fix."
    exit 1
fi
