name: Build and test

on:
  workflow_call:
  push:
    branches: [main]

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build and test project
        run: ./gradlew build

      - name: Publish test results
        if: success() || failure()
        uses: scacap/action-surefire-report@v1
        with:
          report_paths: "**/build/test-results/test/TEST-*.xml"
